### ISSUE TITLE
vpn status

### ISSUE THREAD

**Issue by genofire** [komaflash/ffhb-sopel#1]
http://status.ffhb.tk/data/merged.json
Hier code, eine Art "Cronjob":

https://github.com/sopel-irc/sopel/blob/1cad7977cfb4eca694d654959f0625305584b335/sopel/modules/remind.py

(Mal sehen, wenn ich dazu komme.)

**Comment by malteb247** [comment]
Find ich gut.

**Comment by oliver** [comment]
Es gibt jetzt übrigens auch eine Zusammenfassung der ganzen Messergebnisse, unter http://status.ffhb.tk/data/overall.json - Teile davon könnt man vllt. auch noch vom Bot ausgeben lassen.

**Comment by malteb247** [comment]
Erledigt. Update des Bots mach ich die Tage.

**Comment by genofire** [comment]
seit wann das? cool. Lust wer es zu überarbeiten?

**Comment by oliver** [comment]
@genofire Die Zusammenfassungs-Funktion hatte ich vor ein paar Tagen eingebaut (https://github.com/FreifunkBremen/ffhb-meshmon-html/commit/4486231155581149c5bdcf59a4d12a0622ab2c87 und https://github.com/FreifunkBremen/ffhb-meshmon-html/commit/7ba6ce183578d08dedb66cb7fd24d29a1e352e2e), damit man den Status einfacher in ein Icinga einbinden kann.

**Comment by malteb247** [comment]
@genofire
Irgend was ist da falsch, entweder die Doku oder deine Methode. Teste das mal im Chnnel, hab schon aktualisiert.
