### ISSUE TITLE
Weniger Spam vom VPN-Status-Thread

### ISSUE THREAD

**Issue by malteb247** [komaflash/ffhb-sopel#5]
Folgendes muss erledigt werden:
- zwischenspeichern und nur Untschiede anzeigen.
- Ab 51 Prozent als Fehler melden
- wenn Anfrage kommt und VPN(s) funktionieren, alles okay ausgeben.

**Comment by genofire** [comment]
https://github.com/komaflash/ffhb-ircbot/commit/26b844863ac1403168c5876293ceaf159363507a

Sollte alles drin sein :D

**Comment by malteb247** [comment]
Tip top, danke!  :+1:
